name: focuspulse
description: "Cusomizable Pomodoro Timer with a focus on productivity and user experience."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  just_audio: ^0.10.2
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_500.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/svg/
    - assets/gifs/

  fonts:
    - family: howdy_duck
      fonts:
        - asset: assets/fonts/howdy_duck.ttf
    - family: sebino
      fonts:
        - asset: assets/fonts/sebino-regular.ttf
          weight: 400
