name: focuspulse
description: "Cusomizable Pomodoro Timer with a focus on productivity and user experience."
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  just_audio: ^0.9.46
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6
  google_mobile_ads: ^6.0.0
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_native_splash:
  color: "#FFFFFF" # Background color
  image: assets/images/logo_splashscreen.png # Your splash screen image
  android: true # Generate for Android
  ios: true # Generate for iOS
  android_gravity: center # Image position on Android
  ios_content_mode: center # Image position on iOS
  fullscreen: true # Full screen splash (Android)
  android_12: # Android 12+ specific settings
    image: assets/images/logo_splashscreen.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/svg/
    - assets/gifs/
    - assets/json/

  fonts:
    - family: howdy_duck
      fonts:
        - asset: assets/fonts/howdy_duck.ttf
    - family: sebino
      fonts:
        - asset: assets/fonts/sebino-regular.ttf
          weight: 400
    - family: space_grotesk
      fonts:
        - asset: assets/fonts/space_grotesk/light.ttf
          weight: 300
        - asset: assets/fonts/space_grotesk/regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/semiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/bold.ttf
          weight: 700
